[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install python-dotenv==1.0.0 httpx==0.23.3 openai==1.3.3 pydantic==2.1.1 aiogram==3.0.0",
  "pip install -r requirements.txt || echo 'Some packages could not be installed'"
]

[start]
cmd = "python direct_start.py" 