[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt",
  "chmod +x *.py",
  "ls -la"
]

[phases.build]
cmds = [
  "chmod +x *.py",
  "ls -la"
]

[start]
cmd = "bash -c 'python railway_final.py'" 