[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate"]

[phases.build]
cmds = ["chmod +x bare_minimal.py"]

[start]
cmd = "python bare_minimal.py" 