[build]
builder = "nixpacks"
buildCommand = "chmod +x start.sh && chmod +x install_supabase.sh"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
  [environments.production]
    startCommand = "bash start.sh"

[phases.setup]
cmds = ["chmod +x start.sh", "chmod +x install_supabase.sh", "pip install pydantic==1.10.12"] 