[build]
builder = "nixpacks"
buildCommand = "chmod +x start.sh && chmod +x install_supabase.sh"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100

[environments]
  [environments.production]
    startCommand = "bash start.sh"

[phases.setup]
cmds = ["chmod +x start.sh", "chmod +x install_supabase.sh"] 